[rospy.client][INFO] 2021-12-08 11:09:07,326: init_node, name[/ss42/wheels_driver_node], pid[4723]
[xmlrpc][INFO] 2021-12-08 11:09:07,353: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-12-08 11:09:07,360: Started XML-RPC server [http://ss42.local:35619/]
[rospy.impl.masterslave][INFO] 2021-12-08 11:09:07,361: _ready: http://ss42.local:35619/
[rospy.init][INFO] 2021-12-08 11:09:07,363: ROS Slave URI: [http://ss42.local:35619/]
[rospy.registration][INFO] 2021-12-08 11:09:07,397: Registering with master node http://ss42.local:11311/
[xmlrpc][INFO] 2021-12-08 11:09:07,405: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-12-08 11:09:07,464: registered with master
[rospy.rosout][INFO] 2021-12-08 11:09:07,464: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-08 11:09:07,536: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-08 11:09:07,600: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-08 11:09:07,722: [/ss42/wheels_driver_node] Initializing 
[rospy.internal][INFO] 2021-12-08 11:09:07,830: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-12-08 11:09:08,002: topic[/ss42/wheels_driver_node/emergency_stop] adding connection to [http://ss42.local:41631/], count 0
[rospy.internal][INFO] 2021-12-08 11:09:16,042: topic[/ss42/wheels_driver_node/wheels_cmd] adding connection to [http://ss42.local:33231/], count 0
[rospy.internal][ERROR] 2021-12-08 11:38:48,596: Unable to initiate TCP/IP socket to ss42.local:41990 (http://ss42.local:41631/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-12-08 11:38:49,220: signal_shutdown [signal-2]
[rospy.internal][WARNING] 2021-12-08 11:38:49,395: Unknown error initiating TCP/IP socket to ss42.local:32793 (http://ss42.local:33231/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2021-12-08 11:38:49,403: topic[/ss42/wheels_driver_node/wheels_cmd] removing connection to http://ss42.local:33231/
[rospy.core][INFO] 2021-12-08 11:38:49,459: signal_shutdown [atexit]
