[rospy.client][INFO] 2021-12-06 07:56:19,804: init_node, name[/ss42/wheels_driver_node], pid[5336]
[xmlrpc][INFO] 2021-12-06 07:56:19,818: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2021-12-06 07:56:19,840: ROS Slave URI: [http://ss42.local:38788/]
[xmlrpc][INFO] 2021-12-06 07:56:19,842: Started XML-RPC server [http://ss42.local:38788/]
[rospy.impl.masterslave][INFO] 2021-12-06 07:56:19,843: _ready: http://ss42.local:38788/
[xmlrpc][INFO] 2021-12-06 07:56:19,873: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-06 07:56:19,878: Registering with master node http://ss42.local:11311/
[rospy.init][INFO] 2021-12-06 07:56:19,942: registered with master
[rospy.rosout][INFO] 2021-12-06 07:56:19,944: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-06 07:56:19,988: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-06 07:56:20,033: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-12-06 07:56:20,147: [/ss42/wheels_driver_node] Initializing 
[rospy.internal][INFO] 2021-12-06 07:56:20,300: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-12-06 07:56:21,140: topic[/ss42/wheels_driver_node/emergency_stop] adding connection to [http://ss42.local:40160/], count 0
[rosout][INFO] 2021-12-06 07:56:27,531: [%s] Emergency Stop Activated
[rosout][INFO] 2021-12-06 07:56:28,381: [%s] Emergency Stop Released
[rospy.internal][INFO] 2021-12-06 07:56:35,957: topic[/ss42/wheels_driver_node/wheels_cmd] adding connection to [http://ss42.local:39996/], count 0
[rosout][INFO] 2021-12-06 07:57:08,267: [%s] Emergency Stop Activated
[rosout][INFO] 2021-12-06 07:57:10,001: [%s] Emergency Stop Released
[rospy.internal][ERROR] 2021-12-06 08:03:50,710: Unable to initiate TCP/IP socket to ss42.local:44334 (http://ss42.local:40160/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-12-06 08:03:50,903: signal_shutdown [signal-2]
[rosout][INFO] 2021-12-06 08:03:50,922: [/ss42/wheels_driver_node] Shutting down.
[rospy.internal][INFO] 2021-12-06 08:03:50,967: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-06 08:03:50,969: topic[/ss42/wheels_driver_node/emergency_stop] removing connection to http://ss42.local:40160/
[rospy.internal][INFO] 2021-12-06 08:03:50,975: topic[/ss42/wheels_driver_node/wheels_cmd] removing connection to http://ss42.local:39996/
[rospy.internal][WARNING] 2021-12-06 08:03:50,981: Unknown error initiating TCP/IP socket to ss42.local:44144 (http://ss42.local:39996/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2021-12-06 08:03:50,982: signal-2
[rospy.core][INFO] 2021-12-06 08:03:51,102: signal_shutdown [atexit]
