[rospy.client][INFO] 2021-10-22 13:01:09,490: [32minit_node, name[/ss42/forward_kinematics_node], pid[2194][0m
[xmlrpc][INFO] 2021-10-22 13:01:09,491: [32mXML-RPC server binding to 0.0.0.0:0[0m
[xmlrpc][INFO] 2021-10-22 13:01:09,493: [32mStarted XML-RPC server [http://ss42.local:33719/][0m
[rospy.init][INFO] 2021-10-22 13:01:09,493: [32mROS Slave URI: [http://ss42.local:33719/][0m
[rospy.impl.masterslave][INFO] 2021-10-22 13:01:09,494: [32m_ready: http://ss42.local:33719/[0m
[rospy.registration][INFO] 2021-10-22 13:01:09,496: [32mRegistering with master node http://ss42.local:11311/[0m
[xmlrpc][INFO] 2021-10-22 13:01:09,497: [32mxml rpc node: starting XML-RPC server[0m
[rospy.init][INFO] 2021-10-22 13:01:09,594: [32mregistered with master[0m
[rospy.rosout][INFO] 2021-10-22 13:01:09,595: [32minitializing /rosout core topic[0m
[rospy.rosout][INFO] 2021-10-22 13:01:09,604: [32mconnected to core topic /rosout[0m
[rospy.simtime][INFO] 2021-10-22 13:01:09,609: [32m/use_sim_time is not set, will not subscribe to simulated time [/clock] topic[0m
[rosout][WARNING] 2021-10-22 13:01:09,624: [33m[/ss42/forward_kinematics_node] /home/robotikabot/duckiefleet/calibrations/kinematics/ss42.yaml does not exist. Using default.yaml.[0m
[rosout][INFO] 2021-10-22 13:01:09,668: [32m[/ss42/forward_kinematics_node] ~gain = 1.0 [0m
[rosout][INFO] 2021-10-22 13:01:09,679: [32m[/ss42/forward_kinematics_node] ~trim = 0.0 [0m
[rosout][INFO] 2021-10-22 13:01:09,689: [32m[/ss42/forward_kinematics_node] ~baseline = 0.1 [0m
[rosout][INFO] 2021-10-22 13:01:09,699: [32m[/ss42/forward_kinematics_node] ~radius = 0.0318 [0m
[rosout][INFO] 2021-10-22 13:01:09,710: [32m[/ss42/forward_kinematics_node] ~k = 27.0 [0m
[rosout][INFO] 2021-10-22 13:01:09,729: [32m[/ss42/forward_kinematics_node] Initialized.[0m
[rosout][INFO] 2021-10-22 13:01:09,730: [32m[/ss42/forward_kinematics_node] gain: 1.0 trim: 0.0 baseline: 0.1 radius: 0.0318 k: 27.0[0m
[rospy.internal][INFO] 2021-10-22 13:01:09,748: [32mtopic[/ss42/forward_kinematics_node/velocity] adding connection to [/ss42/velocity_to_pose_node], count 0[0m
[rospy.internal][INFO] 2021-10-22 13:01:09,768: [32mtopic[/ss42/wheels_driver_node/wheels_cmd_executed] adding connection to [http://ss42.local:36696/], count 0[0m
[rospy.internal][INFO] 2021-10-22 13:01:09,824: [32mtopic[/rosout] adding connection to [/rosout], count 0[0m
[rospy.core][INFO] 2021-10-22 13:05:49,451: [32msignal_shutdown [signal-2][0m
[rospy.internal][INFO] 2021-10-22 13:05:49,497: [32mtopic[/ss42/forward_kinematics_node/velocity] removing connection to /ss42/velocity_to_pose_node[0m
[rospy.internal][ERROR] 2021-10-22 13:05:49,550: [31mUnable to initiate TCP/IP socket to ss42.local:33138 (http://ss42.local:36696/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down
[0m
[rospy.internal][INFO] 2021-10-22 13:05:49,573: [32mtopic[/rosout] removing connection to /rosout[0m
[rospy.internal][INFO] 2021-10-22 13:05:49,575: [32mtopic[/ss42/wheels_driver_node/wheels_cmd_executed] removing connection to http://ss42.local:36696/[0m
[rospy.impl.masterslave][INFO] 2021-10-22 13:05:49,576: [32msignal-2[0m
[rospy.core][INFO] 2021-10-22 13:05:50,142: [32msignal_shutdown [atexit][0m
