[rospy.client][INFO] 2021-11-21 06:34:27,510: init_node, name[/ss42/wheels_driver_node], pid[2607]
[xmlrpc][INFO] 2021-11-21 06:34:27,545: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-11-21 06:34:27,547: Started XML-RPC server [http://ss42.local:40566/]
[rospy.impl.masterslave][INFO] 2021-11-21 06:34:27,549: _ready: http://ss42.local:40566/
[rospy.init][INFO] 2021-11-21 06:34:27,554: ROS Slave URI: [http://ss42.local:40566/]
[rospy.registration][INFO] 2021-11-21 06:34:27,567: Registering with master node http://ss42.local:11311/
[xmlrpc][INFO] 2021-11-21 06:34:27,568: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-11-21 06:34:27,655: registered with master
[rospy.rosout][INFO] 2021-11-21 06:34:27,657: initializing /rosout core topic
[rospy.rosout][INFO] 2021-11-21 06:34:27,767: connected to core topic /rosout
[rospy.simtime][INFO] 2021-11-21 06:34:27,864: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-11-21 06:34:28,023: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2021-11-21 06:34:28,047: [/ss42/wheels_driver_node] Initializing 
[rospy.internal][INFO] 2021-11-21 06:34:29,477: topic[/ss42/wheels_driver_node/emergency_stop] adding connection to [http://ss42.local:33000/], count 0
[rospy.internal][INFO] 2021-11-21 06:34:43,704: topic[/ss42/wheels_driver_node/wheels_cmd] adding connection to [http://ss42.local:40512/], count 0
[rosout][INFO] 2021-11-21 06:35:01,679: [%s] Emergency Stop Activated
[rosout][INFO] 2021-11-21 06:35:03,329: [%s] Emergency Stop Released
[rospy.internal][ERROR] 2021-11-21 06:38:18,687: Unable to initiate TCP/IP socket to ss42.local:40777 (http://ss42.local:33000/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2021-11-21 06:38:19,001: signal_shutdown [signal-2]
[rosout][INFO] 2021-11-21 06:38:19,026: [/ss42/wheels_driver_node] Shutting down.
[rospy.internal][INFO] 2021-11-21 06:38:19,096: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-11-21 06:38:19,113: topic[/ss42/wheels_driver_node/emergency_stop] removing connection to http://ss42.local:33000/
[rospy.internal][INFO] 2021-11-21 06:38:19,115: topic[/ss42/wheels_driver_node/wheels_cmd] removing connection to http://ss42.local:40512/
[rospy.impl.masterslave][INFO] 2021-11-21 06:38:19,126: signal-2
[rospy.core][INFO] 2021-11-21 06:38:19,232: signal_shutdown [atexit]
