[rospy.client][INFO] 2021-11-21 07:08:33,555: init_node, name[/ss42/wheels_driver_node], pid[10802]
[xmlrpc][INFO] 2021-11-21 07:08:33,574: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-11-21 07:08:33,577: Started XML-RPC server [http://ss42.local:44862/]
[rospy.impl.masterslave][INFO] 2021-11-21 07:08:33,578: _ready: http://ss42.local:44862/
[rospy.init][INFO] 2021-11-21 07:08:33,584: ROS Slave URI: [http://ss42.local:44862/]
[rospy.registration][INFO] 2021-11-21 07:08:33,621: Registering with master node http://ss42.local:11311/
[xmlrpc][INFO] 2021-11-21 07:08:33,622: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-11-21 07:08:33,685: registered with master
[rospy.rosout][INFO] 2021-11-21 07:08:33,686: initializing /rosout core topic
[rospy.rosout][INFO] 2021-11-21 07:08:33,741: connected to core topic /rosout
[rospy.simtime][INFO] 2021-11-21 07:08:33,785: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2021-11-21 07:08:33,889: [/ss42/wheels_driver_node] Initializing 
[rospy.internal][INFO] 2021-11-21 07:08:33,990: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-11-21 07:08:34,215: topic[/ss42/wheels_driver_node/emergency_stop] adding connection to [http://ss42.local:36150/], count 0
[rospy.internal][INFO] 2021-11-21 07:08:48,150: topic[/ss42/wheels_driver_node/wheels_cmd] adding connection to [http://ss42.local:46656/], count 0
[rosout][INFO] 2021-11-21 07:08:50,863: [%s] Emergency Stop Activated
[rosout][INFO] 2021-11-21 07:08:52,640: [%s] Emergency Stop Released
[rospy.internal][WARNING] 2021-11-21 07:47:11,554: Unknown error initiating TCP/IP socket to ss42.local:44337 (http://ss42.local:36150/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2021-11-21 07:47:11,559: topic[/ss42/wheels_driver_node/emergency_stop] removing connection to http://ss42.local:36150/
[rospy.core][INFO] 2021-11-21 07:47:11,982: signal_shutdown [signal-2]
[rosout][INFO] 2021-11-21 07:47:11,991: [/ss42/wheels_driver_node] Shutting down.
[rospy.internal][INFO] 2021-11-21 07:47:12,047: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2021-11-21 07:47:12,053: Unable to initiate TCP/IP socket to ss42.local:45765 (http://ss42.local:46656/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2021-11-21 07:47:12,056: topic[/ss42/wheels_driver_node/wheels_cmd] removing connection to http://ss42.local:46656/
[rospy.topics][ERROR] 2021-11-21 07:47:12,059: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2021-11-21 07:47:12,060: signal-2
[rospy.core][INFO] 2021-11-21 07:47:12,644: signal_shutdown [atexit]
